### ISSUE TITLE
Public preview UUP

### ISSUE THREAD

**Issue by atplsx** [microsoft/update-server-server-sync#10]
is it possible to integrate  [https://techcommunity.microsoft.com/t5/windows-it-pro-blog/public-preview-of-unified-update-platform-on-premises/ba-p/3659708](url)

**Comment by Almost-Done** [comment]
I believe there were no changes made to the WSUS protocol for UUP-on-premises. I believe the code should be able to find and download UUP updates. Give it a try and open issues if it does not work.

**Comment by atplsx** [comment]
Yes working
